env:
  browser: true
  es6: true
  node: true
  jest: true

extends:
  - google
  - next/core-web-vitals
  - plugin:tailwindcss/recommended

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - "@stylistic"
  - "@stylistic/ts"
  - "@typescript-eslint"
  - react
  - unused-imports

rules:
  # Need to disable this for `unused-imports/no-unused-vars` to work properly
  no-unused-vars:
    - off

  # Need to disable this for `unused-imports/no-unused-vars` to work properly
  "@stylistic/no-unused-vars":
    - off

  unused-imports/no-unused-vars:
    - error
    - varsIgnorePattern: "^[_]+$"
      argsIgnorePattern: "^[_]+$"
      ignoreRestSiblings: true

  unused-imports/no-unused-imports:
    - error

  indent:
    - off

  # Not using `@stylistic/indent` as it has different behavior than the one in `@typescript-eslint/indent`
  "@typescript-eslint/indent":
    - error
    - 2
    - ignoredNodes:
        - TSTypeParameterInstantiation
      MemberExpression: 1

  linebreak-style:
    - error
    - unix

  max-len:
    - error
    - code: 119

  no-console:
    - error
    - allow:
        - info
        - warn
        - error

  # Need to disable this for `@typescript-eslint/no-restricted-imports` to work properly
  no-restricted-imports:
    - off

  "@typescript-eslint/no-restricted-imports":
    - error
    - patterns:
        - group:
            - .*
          message: Only absolute import, such as `@/const/auth` is allowed.

  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
      pathGroups:
        - pattern: react
          group: external
          position: before
      pathGroupsExcludedImportTypes:
        - react
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true

  import/newline-after-import:
    - error
    - count: 2

  "@stylistic/object-curly-spacing":
    - error
    - never

  "@stylistic/semi":
    - error

  "@stylistic/member-delimiter-style":
    - error
    - singleline:
        delimiter: comma
        requireLast: false
      multiline:
        delimiter: comma
        requireLast: true

  "@stylistic/ts/type-annotation-spacing":
    - error
    - before: false
      after: true
      overrides:
        arrow:
          before: true
          after: true

  space-in-parens:
    - error
    - never

  # Typescript will perform this check, no need for React to check it
  react/prop-types:
    - off

  react/jsx-tag-spacing:
    - error
    - beforeSelfClosing: never

  # Most of the dependencies are fine getting the initial value only
  react-hooks/exhaustive-deps:
    - off

  tailwindcss/classnames-order:
    - error

  tailwindcss/no-custom-classname:
    - error

  quote-props:
    - error
    - consistent-as-needed
    - keywords: false
      unnecessary: true

  "@stylistic/arrow-spacing":
    - error
    - before: true
      after: true

  "@stylistic/comma-dangle":
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: always-multiline
      tuples: always-multiline
      enums: always-multiline
      generics: ignore

  "@stylistic/space-unary-ops":
    - error
    - words: true
      nonwords: false

  "@stylistic/space-infix-ops":
    - error

  no-trailing-spaces: error

  padding-line-between-statements:
    - error
    - blankLine: always
      prev: "*"
      next: cjs-export
    - blankLine: always
      prev: "*"
      next: export
    - blankLine: always
      prev: const
      next: cjs-export
    - blankLine: always
      prev: "*"
      next: export

  implicit-arrow-linebreak:
    - error
    - beside

  function-call-argument-newline:
    - error
    - consistent

  operator-linebreak:
    - error
    - after

settings:
  react:
    version: detect
  tailwindcss:
    classRegex: "^class(.*)?$"
